language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: TmoAmFt4bC3/WEi5APMgIhxc3T2E13w3jkizUG1ShADgJpyTPhR6esouIlgjNNfL8g4zyAZYM7XEwNa1vf+TKZZmc7Sbwh3w4QpgoGB2mj5ONBGEW+yMGES97ShDcYrfqpMr2QcVjN3uOkmYRx5TAYlCCa9RUnNXzbs8f8ALcfvrjv3aWBxCkSqAAP21EZrzYjis+fXH8u6n96T2gXWbaRJu3nhRf0czIAAxa8GisjescrJjedwAG7vGicle7G9x29Yew/1IEwx17E+fCKDZW8eZ/FPDDUp1kjX0Gz8Lo6BugB3SpKtHVNr5xISuUsYmttRoIMOFrJJgMDPwp0q0zBeylsGnbxS+vkqbBv3gcoPvSvnpe1bgPMUhLxOj5jXZMU+eOuIxl5GA6uDL+HAzsvW63qFK8Cj/7/J4BXuyHgxpMQ1yTd55ZEJuWz4p3oVQqB4hZ8sbseOAT5bfrbnvJ4qOoQd8CjFJKKdKg/Hm5yEdJ1//Tq/NgivzJhKvbWIX+DtZl6aeTS2SFCLhvD6i1Q/aRyDRfSlacD7Hxe8UdbQUXmv28T9ZQbaFApQbKfacPno7LwFOOny0rLufWOhOAXn7ABIkJKKwHNj7ir3CL8e9fN03/K4RY5DrBzLW2fjKBWiy7M6RGt//IErMAw7p/YcdXJqivtN98px+tMD3Fik=
  app: safe-stream-45800
  on:
    repo: Yakamoose/node-shopping-list-integration-tests
